# Cloudflare Pages configuration
name = "pantrypal"

[build]
command = "npm install --legacy-peer-deps && npm run build"

# The directory where your built assets will be placed
[build.upload]
format = "directory"

# Required for Cloudflare Pages
[site]
bucket = ".next"

# Set the build output directory for Pages
[build.environment]
NODE_VERSION = "20.10.0"
NPM_VERSION = "10.2.3"
NODE_COMPAT = "true"

# This is the key parameter for Cloudflare Pages
pages_build_output_dir = ".next" 