# Cloudflare Pages configuration
name = "stock-recorder"  # Make sure this matches your project name in Cloudflare

# Build command settings - not used in our deployment but kept for direct Wrangler usage
[build]
command = "npm run build"

# Set the build output directory for Pages (this is critical)
pages_build_output_dir = ".vercel/output/static"

# Build environment settings
[build.environment]
NODE_VERSION = "18.0.0"
NPM_VERSION = "9.6.7"
NODE_COMPAT = "true"

# Define site configuration
[site]
bucket = ".vercel/output/static"

# The directory where your built assets will be placed
[build.upload]
format = "directory"
# Exclude cache files and other large files
exclude = [
  ".next/cache/**",
  "cache/**",
  "**/*.pack",
  "**/*.map",
  "node_modules/**",
  ".git/**",
  ".next/types/**"
]

# Worker configuration
[worker]
compatibility_date = "2023-10-30"
compatibility_flags = ["streams_enable_constructors"]
usage_model = "bundled" 